// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEip3009$Type } from "./IEip3009";
import { PaidAccessRegistry$Type } from "./PaidAccessRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEip3009"]: IEip3009$Type;
    ["PaidAccessRegistry"]: PaidAccessRegistry$Type;
    ["contracts/PaidAccessRegistry.sol:IEip3009"]: IEip3009$Type;
    ["contracts/PaidAccessRegistry.sol:PaidAccessRegistry"]: PaidAccessRegistry$Type;
  }

  interface ContractTypesMap {
    ["IEip3009"]: GetContractReturnType<IEip3009$Type["abi"]>;
    ["PaidAccessRegistry"]: GetContractReturnType<PaidAccessRegistry$Type["abi"]>;
    ["contracts/PaidAccessRegistry.sol:IEip3009"]: GetContractReturnType<IEip3009$Type["abi"]>;
    ["contracts/PaidAccessRegistry.sol:PaidAccessRegistry"]: GetContractReturnType<PaidAccessRegistry$Type["abi"]>;
  }
}
