// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IEip3009$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IEip3009",
  "sourceName": "contracts/PaidAccessRegistry.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "validAfter",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "validBefore",
          "type": "uint256"
        },
        {
          "internalType": "bytes32",
          "name": "nonce",
          "type": "bytes32"
        },
        {
          "internalType": "uint8",
          "name": "v",
          "type": "uint8"
        },
        {
          "internalType": "bytes32",
          "name": "r",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "transferWithAuthorization",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IEip3009",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEip3009$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/PaidAccessRegistry.sol:IEip3009",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEip3009$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IEip3009",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEip3009$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/PaidAccessRegistry.sol:IEip3009",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEip3009$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IEip3009",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEip3009$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/PaidAccessRegistry.sol:IEip3009",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEip3009$Type["abi"]>>;
}
