// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPriceOracle$Type } from "./IPriceOracle";
import { SettlementLedger$Type } from "./SettlementLedger";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPriceOracle"]: IPriceOracle$Type;
    ["SettlementLedger"]: SettlementLedger$Type;
    ["contracts/SettlementLedger.sol:IPriceOracle"]: IPriceOracle$Type;
    ["contracts/SettlementLedger.sol:SettlementLedger"]: SettlementLedger$Type;
  }

  interface ContractTypesMap {
    ["IPriceOracle"]: GetContractReturnType<IPriceOracle$Type["abi"]>;
    ["SettlementLedger"]: GetContractReturnType<SettlementLedger$Type["abi"]>;
    ["contracts/SettlementLedger.sol:IPriceOracle"]: GetContractReturnType<IPriceOracle$Type["abi"]>;
    ["contracts/SettlementLedger.sol:SettlementLedger"]: GetContractReturnType<SettlementLedger$Type["abi"]>;
  }
}
