// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IPriceOracle$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IPriceOracle",
  "sourceName": "contracts/SettlementLedger.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "marketId",
          "type": "bytes32"
        }
      ],
      "name": "getPrice",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "price",
          "type": "uint256"
        },
        {
          "internalType": "uint64",
          "name": "updatedAt",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/SettlementLedger.sol:IPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/SettlementLedger.sol:IPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/SettlementLedger.sol:IPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
}
