// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PriceOracle$Type } from "./PriceOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PriceOracle"]: PriceOracle$Type;
    ["contracts/PriceOracle.sol:PriceOracle"]: PriceOracle$Type;
  }

  interface ContractTypesMap {
    ["PriceOracle"]: GetContractReturnType<PriceOracle$Type["abi"]>;
    ["contracts/PriceOracle.sol:PriceOracle"]: GetContractReturnType<PriceOracle$Type["abi"]>;
  }
}
