// Extract compiled contract ABIs into typed `as const` modules so viem gets full
// type inference. Re-run after changing the contracts: `pnpm --filter
// @fangorn-market/shared sync-abi` (requires the contracts to be compiled first).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifacts = resolve(here, "../../../contracts/artifacts/contracts");
const outDir = resolve(here, "../src/abi");
mkdirSync(outDir, { recursive: true });

const contracts = ["PriceOracle", "SettlementLedger"];

for (const name of contracts) {
  const artifactPath = resolve(artifacts, `${name}.sol/${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const body = `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  writeFileSync(resolve(outDir, `${name}.ts`), body);
  console.log(`wrote src/abi/${name}.ts (${artifact.abi.length} entries)`);
}
