// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockUSDC$Type } from "./MockUSDC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockUSDC"]: MockUSDC$Type;
    ["contracts/MockUSDC.sol:MockUSDC"]: MockUSDC$Type;
  }

  interface ContractTypesMap {
    ["MockUSDC"]: GetContractReturnType<MockUSDC$Type["abi"]>;
    ["contracts/MockUSDC.sol:MockUSDC"]: GetContractReturnType<MockUSDC$Type["abi"]>;
  }
}
