// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DataRegistry$Type } from "./DataRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DataRegistry"]: DataRegistry$Type;
    ["contracts/DataRegistry.sol:DataRegistry"]: DataRegistry$Type;
  }

  interface ContractTypesMap {
    ["DataRegistry"]: GetContractReturnType<DataRegistry$Type["abi"]>;
    ["contracts/DataRegistry.sol:DataRegistry"]: GetContractReturnType<DataRegistry$Type["abi"]>;
  }
}
